name: hd2-website-dev
version: '0.1'

services:
  app:
    image: hd2-website-dev
    build: 
    ports:
      - 3000:3000
    volumes:
      - ./pages:/home/bun/app/pages
      - ./public:/home/bun/app/public
      - ./styles:/home/bun/app/styles
      - ./components:/home/bun/app/components
